repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=119", "--ignore=E203,W503"]
        additional_dependencies: ["flake8-isort"]

  - repo: https://github.com/OCA/pylint-odoo
    rev: 9.0.3.3.1
    hooks:
      - id: pylint_odoo
        args:
          [
            "-d",
            "missing-final-newline,trailing-newlines,fixme,pointless-statement,too-few-public-methods",
          ]
        additional_dependencies: ["pylint", "pycodestyle", "pydocstyle"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: "(.*/migrations/.*.py)|(.*custom_addons.*.py)"