version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: "@HCsinergia2025"  # ¡Usa la contraseña de prueba!
      POSTGRES_DB: odoo_db  # Base de datos para desarrollo
    volumes:
      - db_data:/var/lib/postgresql/data  # Named volume
    ports:
      - "5432:5432"

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8888:8888"
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ../../custom_addons:/mnt/custom_addons
      - ../../extra_addons:/mnt/extra_addons
      - odoo_web_data:/var/lib/odoo  # Named volume
      - ./typings:/opt/odoo/typings #  volume para pyright
    environment:
      HOST: db
      DB_USER: odoo
      DB_PASSWORD: "@HCsinergia2025"  # ¡Usa la contraseña de prueba!
      DB_NAME: odoo_db  # DB name para desarrollo
      ODOO_ADMIN_PASSWORD: "@HCsinergia2025"  # ¡Usa la contraseña de prueba!
    # No entrypoint override. Use the CMD from the Dockerfile

volumes: # Declare named volumes
    db_data:
    odoo_web_data: