odoo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8888:8888"  # Puerto para debugpy
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ../../custom_addons:/mnt/custom_addons
      - ../../extra_addons:/mnt/extra_addons
      - ../../odoo-web-data:/var/lib/odoo
    environment:
      HOST: db
      DB_USER: odoo
      DB_PASSWORD: myodoo  # ¡CAMBIA ESTO EN PRODUCCIÓN!
      DB_NAME: postgres
      ODOO_ADMIN_PASSWORD: admin  # ¡CAMBIA ESTO EN PRODUCCIÓN!
    entrypoint: /opt/odoo/odoo-bin -c /etc/odoo/odoo.conf --stop-after-init -d odoo -i base --test-enable
