version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: "@HCsinergia2025"
      POSTGRES_DB: odoo_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8888:8888" #Debug port
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ../../custom_addons:/mnt/custom_addons
      - ../../extra_addons:/mnt/extra_addons
      - odoo_web_data:/var/lib/odoo
      - ./typings:/opt/odoo/typings
    environment:
      HOST: db
      USER: odoo # Odoo non-root user
      PASSWORD: "@HCsinergia2025"
      ODOO_ADMIN_PASSWORD: "@HCsinergia2025"
    networks: # Add network configuration
      - odoo_network

volumes:
  db_data:
  odoo_web_data:

networks: # Define the network
  odoo_network:
    driver: bridge