#name: CD  # Nombre del workflow

#on:
#  push:
#    branches:
#      - main  # Desplegar solo cuando se hace push a la rama main

#jobs:
#  deploy:
#    runs-on: ubuntu-latest  # Usar una máquina virtual Ubuntu
#    steps:
#      - uses: actions/checkout@v3  # Clonar el repositorio

#      - name: Deploy to Server
#        uses: appleboy/ssh-action@master  # Usar la acción ssh-action
#        with:
#          host: ${{ secrets.SSH_HOST }}       # Host del servidor (secreto)
#          username: ${{ secrets.SSH_USER }}   # Usuario SSH (secreto)
#          key: ${{ secrets.SSH_KEY }}        # Clave privada SSH (secreto)
#          port: ${{ secrets.SSH_PORT }}    #Puerto ssh, por defecto 22
#          script: |                      # Comandos a ejecutar en el servidor
#            cd /path/to/your/odoo-deploy  #  Cambia esto a la ruta correcta en tu servidor!
#            git pull origin main          #  Obtener los últimos cambios
#            cd versions/17.0/
#            docker-compose down           #  Detener los contenedores antiguos
#            docker-compose up -d --build  #  Construir y ejecutar los contenedores
