name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        odoo_version: ["17.0"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8  # Herramientas de linting
          python -m pip install -r versions/${{ matrix.odoo_version }}/requirements.txt
          python -m pip install pre-commit

      - name: Run pre-commit
        run: |
            pre-commit run --all-files

      - name: Build Docker image
        run: |
          docker-compose -f versions/${{ matrix.odoo_version }}/docker-compose.yml build

      - name: Run tests
        run: |
          docker-compose -f versions/${{ matrix.odoo_version }}/docker-compose.yml up -d db
          docker-compose -f versions/${{ matrix.odoo_version }}/docker-compose.yml run --rm odoo odoo-bin -c /etc/odoo/odoo.conf -d odoo_test --stop-after-init --test-enable

      - name: Pyright check (Optional)
        if: ${{ always() }}
        run: |
            python -m pip install pyright
            pyright --project versions/${{ matrix.odoo_version }}/pyrightconfig.json