name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r versions/17.0/requirements.txt
          python -m pip install pre-commit

      - name: Run pre-commit
        run: |
          pre-commit run --all-files

      - name: Build Docker image
        run: |
          cd versions/17.0 && docker-compose build

      - name: Run tests
        run: |
          cd versions/17.0 && docker-compose run --rm odoo odoo-bin -c /etc/odoo/odoo.conf -d odoo_test --stop-after-init --test-enable